AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  # API gateway
  APIgateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      Auth:
        Authorizers:
          MainAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
        DefaultAuthorizer: MainAuthorizer
  # Draw a card function
  DrawFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: draw/
      Handler: app.lambda_handler
      Runtime: python3.9
      Policies:
        - AmazonDynamoDBFullAccess
      Architectures:
        - x86_64
      Events:
        APIaccess:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /draw
            Method: get
            RestApiId: !Ref APIgateway
  # DynamoDB game table
  GameTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: backgammon-table 
      PrimaryKey:
        Type: String
        Name: uid
  # User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: UserPoolBackgammon
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: true
  # User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: UserPoolClientBackgammon
      GenerateSecret: false


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${APIgateway}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  UserPoolClientId:
    Description: "User pool client id"
    Value: !Ref UserPoolClient


